export const books = [
  {
    id: 1,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publisher: 'HarperCollins',
    year: 1960,
    image: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41j-s9fHJcL.jpg',
    price: 9.99,
    read: 'None',
  },
  {
    id: 2,
    title: '1984',
    author: 'George Orwell',
    publisher: 'Penguin Books',
    year: 1949,
    image: 'https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg',
    price: 8.99,
    read: 'currentlyReading',
  },
  {
    id: 3,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    publisher: 'Little, Brown and Company',
    year: 1951,
    image: 'https://i0.wp.com/saltyasiangirl.com/wp-content/uploads/2021/05/unnamed.jpg?fit=512%2C512&ssl=1',
    price: 10.99,
    read: 'currentlyReading',
  },
  {
    id: 4,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    publisher: 'Scribner',
    year: 1925,
    image: 'https://m.media-amazon.com/images/I/71FTb9X6wsL.jpg',
    price: 7.99,
    read: 'Read',
  },
  {
    id: 5,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    publisher: 'Harper Perennial Modern Classics',
    year: 1932,
    image: 'https://pagdandi.org/wp-content/uploads/2021/04/Brave-New-World.jpg',
    price: 12.99,
    read: 'wantToRead',
  },
  {
    id: 6,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publisher: 'Penguin Classics',
    year: 1813,
    image: 'https://m.media-amazon.com/images/I/71Q1tPupKjL.jpg',
    price: 6.99,
    read: 'Read',
  },
];
